const progression=[['Borgo Foglianova','Città'],['Percorso 29','Percorso'],['Fiorpescopoli','Città'],['Percorso 30','Percorso'],['Percorso 31','Percorso'],['Violapoli','Città'],['Torre Sprout','Edificio'],['Rovine d’Alfa','Area'],['Percorso 32','Percorso'],['Grotta di mezzo','Grotta'],['Percorso 33','Percorso'],['Azalina','Città'],['Pozzo Slowpoke','Grotta'],['Bosco di Lecci','Area'],['Percorso 34','Percorso'],['Fiordoropoli','Città'],['Percorso 35','Percorso'],['Parco Nazionale','Area'],['Percorso 36','Percorso'],['Percorso 37','Percorso'],['Amarantopoli','Città'],['Torre Bruciata','Edificio'],['Percorso 38','Percorso'],['Percorso 39','Percorso'],['Olivinopoli','Città'],['Faro di Olivinopoli','Edificio'],['Percorso 40','Percorso'],['Percorso 41','Percorso'],['Isole Vorticose','Grotta'],['Fiorlisopoli','Città'],['Percorso 47','Percorso'],['Grotta Falesia','Grotta'],['Percorso 48','Percorso'],['Zona Safari','Area'],['Percorso 42','Percorso'],['Monte Scodella','Grotta'],['Mogania','Città'],['Lago d’Ira','Area'],['Percorso 43','Percorso'],['Torre Radio','Edificio'],['Percorso 44','Percorso'],['Via Gelata','Grotta'],['Ebanopoli','Città'],['Tana del Drago','Grotta'],['Percorso 45','Percorso'],['Percorso 46','Percorso'],['Percorso 27','Percorso'],['Cascate Tohjo','Grotta'],['Percorso 26','Percorso'],['Via Vittoria','Grotta'],['Altopiano Blu','Città'],['S.S. Acqua','Area'],['Aranciopoli','Città'],['Zafferanopoli','Città'],['Azzurropoli','Città'],['Fucsiapoli','Città'],['Lavandonia','Città'],['Celestopoli','Città'],['Plumbeopoli','Città'],['Biancavilla','Città'],['Isola Cannella','Città'],['Smeraldopoli','Città'],['Monte Argento','Area']];
const places=progression.map((x,i)=>({name:x[0],kind:x[1],region:i<51?'Johto':'Kanto'}));
const connections={'Percorso 32':[['↑ Nord','Violapoli'],['← Ovest','Rovine d’Alfa'],['↓ Sud','Grotta di mezzo']],'Grotta di mezzo':[['↑ Nord','Percorso 32'],['↓ Sud','Percorso 33']],'Percorso 33':[['↑ Nord','Grotta di mezzo'],['← Ovest','Azalina']],'Violapoli':[['→ Est','Percorso 31'],['↓ Sud','Percorso 32'],['↙ Sud-ovest','Rovine d’Alfa']]};
const info={
'Percorso 32':{summary:'Quarto percorso della storia, da Violapoli alla Grotta di mezzo.',items:[['Repellente','Nell’erba alta, a ovest della Picnic Girl Liz.'],['Miracolseme','Dall’uomo che prima bloccava il percorso.'],['Mega Ball','A sudovest del molo, nella zona erbosa.'],['Amo Vecchio','Dal Guru Pescatore nel Centro Pokémon.'],['Esca Ball ×2','Dal fan di Franz nel Centro Pokémon.'],['MT05 Boato','Da un uomo a nord del percorso, oltre l’albero da tagliare.'],['Superpozione','Nascosta dietro l’uomo che dà MT05; richiede Taglio.'],['MT09 Semitraglia','Sulla barriera a ovest del Bullo Nerino.'],['Conchinella','Dietro una roccia frantumabile vicino alla Grotta di mezzo.'],['Squama Cuore','Nascosta vicino al pilastro del Supertreno; richiede Surf.'],['Mega Ball','Nascosta vicino all’ingresso della Grotta di mezzo.']],npcs:[['Guru Pescatore','Regala Amo Vecchio nel Centro Pokémon.'],['Fan di Franz','Regala 2 Esca Ball nel Centro Pokémon.'],['Veronica','Di venerdì regala Velenaculeo; agli incontri successivi Fiocco Relax.']],tasks:['Prendi Amo Vecchio','Prendi le 2 Esca Ball','Raccogli MT09 Semitraglia','Entra nella Grotta di mezzo']},
'Grotta di mezzo':{summary:'Prima grotta obbligatoria. Collega Percorso 32 e Percorso 33; i piani inferiori portano alle Rovine d’Alfa.',items:[['Attacco X','Piano terra, nella zona nord-occidentale.'],['MT39 Rocciotomba','Piano terra, vicino all’uscita sud.'],['Mega Ball','Piano terra, lungo il percorso principale.'],['Sveglia','Primo piano sotterraneo.'],['Iperpozione','Primo piano sotterraneo; richiede Surf.']],npcs:[['Allenatori della grotta','Avventurieri e Mangiafuoco lungo il percorso.']],tasks:['Attraversa la grotta','Torna di venerdì dopo Angelo per Lapras','Esplora i sotterranei con Surf']},
'Violapoli':{summary:'Prima città con Palestra, Torre Sprout e accesso alle Rovine d’Alfa.',items:[['Onix Rocky','Scambio con Bellsprout nella casa a sud-ovest.'],['Uovo speciale','Al Centro Pokémon tramite Primo: Mareep, Wooper o Slugma.']],npcs:[['Primo','Sblocca l’uovo speciale.'],['Allenatore dello scambio','Scambia Bellsprout per Onix.']],tasks:['Completa Torre Sprout','Batti Valerio']},
'Rovine d’Alfa':{summary:'Area archeologica con quattro puzzle e le 28 forme di Unknown.',items:[],npcs:[['Ricercatori','Aggiornano il rapporto Unknown.']],tasks:['Completa i quattro puzzle','Cattura tutte le 28 forme']}
};
const natures=[['Ardita','—','—'],['Schiva','Difesa','Attacco'],['Sicura','Difesa','Attacco'],['Fiacca','Difesa','Dif. Speciale'],['Placida','Difesa','Velocità'],['Decisa','Attacco','Att. Speciale'],['Docile','—','—'],['Birbona','Attacco','Dif. Speciale'],['Audace','Attacco','Velocità'],['Modesta','Att. Speciale','Attacco'],['Mite','Att. Speciale','Difesa'],['Timida','Velocità','Attacco'],['Lesta','Velocità','Difesa'],['Seria','—','—'],['Allegra','Velocità','Att. Speciale'],['Ingenua','Velocità','Dif. Speciale'],['Calma','Dif. Speciale','Attacco'],['Gentile','Dif. Speciale','Difesa'],['Cauta','Dif. Speciale','Att. Speciale'],['Vivace','Dif. Speciale','Velocità'],['Furba','Difesa','Att. Speciale'],['Ardente','Att. Speciale','Dif. Speciale'],['Ostinata','Attacco','Difesa'],['Quieta','Att. Speciale','Velocità'],['Scaltra','Difesa','Att. Speciale']];
const gyms=[
['Valerio','Violapoli',13,[['Pidgey',9],['Pidgeotto',13]],[['Piumino Abe','Spearow Lv 9'],['Piumino Rodolfo','Pidgey Lv 7 · Pidgey Lv 7']]],
['Raffaello','Azalina',17,[['Scyther',17],['Metapod',15],['Kakuna',15]],[['Gemelle Amy e Mimi','Ledyba Lv 10 · Spinarak Lv 10'],['Pigliamosche Al','Caterpie Lv 12 · Weedle Lv 12'],['Pigliamosche Benny','Weedle Lv 7 · Kakuna Lv 9 · Beedrill Lv 12']]],
['Chiara','Fiordoropoli',19,[['Clefairy',17],['Miltank',19]],[['Bellezza Victoria','Sentret Lv 9 ×3'],['Bellezza Samantha','Meowth Lv 16 ×2'],['Bellezza Brigida','Jigglypuff Lv 15 ×3'],['Scolara Carrie','Snubbull Lv 17']]],
['Angelo','Amarantopoli',25,[['Gastly',21],['Haunter',21],['Haunter',23],['Gengar',25]],[['Sensitivo Jeffrey','Haunter Lv 22'],['Sensitivo Ping','Gastly Lv 16 ×5'],['Medium Martha','Gastly Lv 18 · Haunter Lv 20'],['Medium Grace','Haunter Lv 20 · Haunter Lv 20']]],
['Furio','Fiorlisopoli',31,[['Primeape',29],['Poliwrath',31]],[['Karateka Yoshi','Hitmonlee Lv 27'],['Karateka Lao','Hitmonchan Lv 27'],['Karateka Nob','Machop Lv 25 · Machoke Lv 25'],['Karateka Lung','Mankey Lv 23 ×2 · Primeape Lv 25']]],
['Jasmine','Olivinopoli',35,[['Magnemite',30],['Magnemite',30],['Steelix',35]],[['Nessun allenatore interno','—']]],
['Alfredo','Mogania',34,[['Seel',30],['Dewgong',32],['Piloswine',34]],[['Snowboarder Ronald','Swinub Lv 27 ×2'],['Sciatrice Clarissa','Jynx Lv 29'],['Sciatore Maurizio','Dewgong Lv 29']]],
['Sandra','Ebanopoli',41,[['Gyarados',38],['Dragonair',38],['Dragonair',38],['Kingdra',41]],[['Fantallenatore Paulo','Dratini Lv 35 ×2 · Seadra Lv 35'],['Fantallenatore Lola','Dratini Lv 35 · Dragonair Lv 37'],['Gemelle Lea e Pia','Dratini Lv 35 ×2']]]
];
